### ISSUE TITLE
Add Groups

### ISSUE THREAD

**Issue by mbramson** [ElixirCLE/pairmotron#10]
Add groups so that users can be members of (multiple groups per user? Some more thinking here). Each user would then be paired within their own group.

There would need to be some sort of way to decide which group you were looking at in the page controller. The displayed pairs would filter accordingly.

Projects would also need to be associated with groups.

It would be nice if there was an invite mechanism for groups, so that the user that creates a group becomes an admin of that group, and is then the one that distributes invites to the group.

**Comment by ericworkman** [comment]
What are you trying to accomplish with groups?

**Comment by mbramson** [comment]
This is something that makes more sense once users can authenticate, as a user would only be able to see the pairs within their own group (up for debate?) and would only see projects for their specific group. A group would be a hard line for which no user in one group could pair with a user in a separate group.

Somewhere down the line, I'd like to implement something allowing users to specify certain subjects/projects that they'd like to pair on or would be open to pair on, and have the pairing mechanism take that into account when generating pairs, but those would all still be among the same group.

So for our current purposes, we would all be in the same group. Most likely every single person in the company would be in the same group. But whenever you wanted a hard line between multiple groups of people, groups would be the go to. This would also separate any metrics/analytics implemented at some future date.

**Comment by cweisel** [comment]
As an admin, I'd like to be able to create new groups of people to form pairs, so that I can use pairmrotron for multiple different purposes. 

As a user, I'd like to be able to join different groups, so that I can participate in different activities.

As an admin, I'd like to be able to add people to a group on their behalf, so I can set up a group with everyone that belongs there.

In particular, I (Chris) would like to be able to use pairmrotron to set up Mr. Rogers sessions in the Payer vertical each week.
