### ISSUE TITLE
First week of the year via Timex.iso_week

### ISSUE THREAD

**Issue by ericworkman** [ElixirCLE/pairmotron#28]
Timex.iso_week implements [ISO weeks](https://en.wikipedia.org/wiki/ISO_week_date) which have an interesting implication for the first week of the year. The first ISO week of the year is the first week with a Thursday in it. For example, January 1, 2005 lands on a Saturday. Its ISO week is 2004 week 53.

This gets us in trouble if we want to look up a pair for the first week of January. January 1, 2016 was 2015 week 53. We should consider replacing Timex.iso_week with something more natural, change the /year/week lookup to a date (so ISO week can be calculated), or by adding the covered dates to the pair page.

This won't affect us for 2017 or 2018 at least, but its something to consider. @mbramson discovered this issue.

**Comment by mbramson** [comment]
This causes a strange situation when the first of the year lies on a Thursday, Wednesday, or Tuesday. When the user logs in on the Monday before January 1st, it will still be December, but the top of main pairing page will say "Week 1 of <next year>", which might be confusing for the user.

As an example, January 1st, 2015, is on a Thursday. If a user checked pairs on Monday, December 29th, 2014, at the top of the main page it would say "Pairs for Week 1 of 2015", despite the fact that it is still 2014.

Speaking with @ericworkman it looks like there are two viable solutions to this problem:
1. Redefine the week such that the 1st week of the year is the first week with a Monday in it.
2. Keep the ISOWeek on the backend (since it is consistent and unique) and instead of displaying Week # of Year #, display a range of dates. Keeping with the example above, instead of "Pairs for Week 1 of 2015", display "Pairs from 12/29/2014 to 1/4/2015".
   - Note: the show route for that week would still be /2015/1

We should probably discuss and decide on one of these approaches and then close this card in favor of a new one with that specific solution.

**Comment by ericworkman** [comment]
> when the first of the year lies on a Thursday, Wednesday, or Tuesday. 

I think the disconnect occurs whenever the work week is split between December and January.

As we discussed, I like 2) better. If we also add links to the previous week and the next week, we'd have a straight forward way of correcting mistaken week lookups.

**Comment by mbramson** [comment]
Should've expressed in my comment above, I also like option 2 better. And good call on the next and previous week buttons.

**Comment by mbramson** [comment]
Closing in favor of #30
